### ISSUE TITLE
Unknown Extension: blog

### ISSUE THREAD

**Issue by bensheldon** [simonrice/middleman-rspec#4]
I'm having trouble following this pattern with extensions. Would you be able to update this example when adding `middleman-blog` to the gemfile? I'm currently getting this erroring out when trying to run on my own blog:

``` bash
Bens-MacBook-Pro:island94-middleman bensheldon$ bundle exec rspec
== Unknown Extension: blog
/Users/bensheldon/.gem/ruby/2.1.0/gems/middleman-core-3.2.2/lib/middleman-core/configuration.rb:78:in `method_missing': undefined local variable or method `blog' for #<Middleman::Application:0x70175303677540> (NameError)
    from /Users/bensheldon/Workspace/island94-middleman/config.rb:154:in `block in initialize'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/middleman-core-3.2.2/lib/vendored-middleman-deps/hooks-0.2.0/lib/hooks.rb:53:in `instance_exec'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/middleman-core-3.2.2/lib/vendored-middleman-deps/hooks-0.2.0/lib/hooks.rb:53:in `block in run_hook_for'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/middleman-core-3.2.2/lib/vendored-middleman-deps/hooks-0.2.0/lib/hooks.rb:49:in `each'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/middleman-core-3.2.2/lib/vendored-middleman-deps/hooks-0.2.0/lib/hooks.rb:49:in `run_hook_for'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/middleman-core-3.2.2/lib/vendored-middleman-deps/hooks-0.2.0/lib/hooks.rb:107:in `run_hook'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/middleman-core-3.2.2/lib/middleman-core/core_extensions/request.rb:53:in `inst'
    from /Users/bensheldon/Workspace/island94-middleman/spec/spec_helper.rb:5:in `<top (required)>'
    from /Users/bensheldon/Workspace/island94-middleman/spec/features/index_spec.rb:1:in `require'
    from /Users/bensheldon/Workspace/island94-middleman/spec/features/index_spec.rb:1:in `<top (required)>'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `each'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load_spec_files'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:22:in `run'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
    from /Users/bensheldon/.gem/ruby/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'
```

**Comment by pabuisson** [comment]
Hey @bensheldon ! Did you have any success in this ? I'm currently trying to test some helpers in my middleman-blog, but having troubles with it, because of the ``activate :blog { |blog| ... }`` block.

Requiring ``middleman-blog`` does not seem to do the trick for me.

**Comment by johnrlive** [comment]
I commented out the following and the error went away. Not sure why, anyone care enough to explain?

#require 'rubygems'
#require 'middleman/rack'
#run Middleman.server
